# Simple .travis.yml

language: node_js
node_js:
  - "node"
  - "7"
#   - "6" # async requires node 7+

addons:
  code_climate:
    repo_token: 0a7eff0b23b2ac71d08ccd39d3419f2ac50fb91d01b830fec1a002ecf20a41cf

notifications:
  email:
    on_success: change
    on_failure: change

services:
  - postgresql

before_script:
  - psql -c "CREATE USER testu WITH LOGIN CREATEDB PASSWORD 'my secret password';" -U postgres
  - export PGPASSWORD="my secret password"
  - psql -c 'create database atestdb;' -U testu -d postgres
  - psql -c 'create schema archive;' -U testu -d atestdb
  - psql -c 'create schema lookups;' -U testu -d atestdb
  - echo "{\"postgresql\":{\"host\":\"127.0.0.1\",\"port\":5432,\"username\":\"testu\",\"signatures_db\":\"atestdb\"}}" > test.config.json && chmod 0600 test.config.json
  - echo "{\"postgresql\":{\"host\":\"127.0.0.1\",\"port\":5432,\"username\":\"testu\",\"signatures_db\":\"atestdb\"}}" > app1.test.config.json && chmod 0600 app1.test.config.json
  - echo "{\"postgresql\":{\"host\":\"127.0.0.1\",\"port\":5432,\"username\":\"testu\",\"signatures_db\":\"atestdb\"},"detstaid",7003}" > app2.test.config.json && chmod 0600 app2.test.config.json
  - mkdir data
  - mkdir data2

after_success:
  - npm install codeclimate-test-reporter
  - ./node_modules/.bin/tap --coverage-report=text-lcov | ./node_modules/.bin/codeclimate-test-reporter
